### ISSUE TITLE
Current master build's dependencies are in conflict

### ISSUE THREAD

**Issue by danieldekay** [assafelovic/gpt-researcher#1115]
Poetry won't resolve the different versions in the langchain family of modules, as they are too restrictive.

I don't want to play around fixing numbers randomly, in case the limitation has a solid reason.

```
Because no versions of langchain-gigachat match >0.3.3,<0.3.4 || >0.3.4,<0.4.0
 and langchain-gigachat (0.3.3) depends on langchain-core (>=0.3,<0.4), langchain-gigachat (>=0.3.3,<0.3.4 || >0.3.4,<0.4.0) requires langchain-core (>=0.3,<0.4).
And because langchain-gigachat (0.3.4) depends on langchain-core (>=0.3,<0.4)
 and gpt-researcher (0.8.5) @ git+https://github.com/assafelovic/gpt-researcher.git@master depends on langchain-gigachat (^0.3.3), gpt-researcher (0.8.5) @ git+https://github.com/assafelovic/gpt-researcher.git@master requires langchain-core (>=0.3,<0.4).```

**Comment by chrishart0** [comment]
https://github.com/assafelovic/gpt-researcher/issues/1106

**Comment by assafelovic** [comment]
Hey pushed this now: https://github.com/assafelovic/gpt-researcher/commit/629c1293ccb3fe6b2ba4c2a039880ac49accbe0e

Can you pull and see if it resolves the issue?

**Comment by danieldekay** [comment]
Yes, this installs again. Is there a reason we don't go to 0.3 yet?

```toml
[tool.poetry.dependencies]
python = ">=3.11,<3.12"
gpt-researcher = { git = "https://github.com/assafelovic/gpt-researcher.git", branch = "master" }
langchain = "^0.2"
langchain-core = "^0.2"
langgraph = "^0.2"

```
