### ISSUE TITLE
Docker build is missing langchain packages

### ISSUE THREAD

**Issue by azertylr** [assafelovic/gpt-researcher#1126]
**Describe the bug**
Hello,
When building the docker image, some langchain packages are missing. At least langchain-google-genai and langchain-mistralai

**To Reproduce**
Run with the following docker file:

````yaml
services:
  gpt-researcher:
    build: https://github.com/assafelovic/gpt-researcher.git
    environment: 
      GOOGLE_API_KEY: 
      LOGGING_LEVEL: INFO
      FAST_LLM: "google_genai:gemini-1.5-flash"
      SMART_LLM: "google_genai:gemini-1.5-pro"
      STRATEGIC_LLM: "google_genai:gemini-1.5-pro"
      EMBEDDING: "google_genai:models/text-embedding-004"
    volumes:
      - /home/docker/gptr/my-docs:/usr/src/app/my-docs:rw
      - /home/docker/gptr/outputs:/usr/src/app/outputs:rw
      - /home/docker/gptr/logs:/usr/src/app/logs:rw
    restart: always
    ports:
      - 8000:8000
````

There is an error, saying langchain_google_genai is missing.

Running pip install langchain_google_genai in the container solves the problem.

**Additional context**

Docker engine: 27.5.1
Host: ubuntu 24.04
