### ISSUE TITLE
Install via Docker fails on Mac M2

### ISSUE THREAD

**Issue by cristianstoica** [assafelovic/gpt-researcher#1201]
**Describe the bug**
Installation via Docker fails with the below output

`6.295 E: Unable to locate package google-chrome-stable
------
failed to solve: process "/bin/sh -c apt-get update     && apt-get install -y gnupg wget ca-certificates --no-install-recommends     && wget -qO - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -     && echo \"deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main\" > /etc/apt/sources.list.d/google-chrome.list     && apt-get update     && apt-get install -y google-chrome-stable chromium-driver     && google-chrome --version && chromedriver --version     && apt-get install -y --no-install-recommends firefox-esr build-essential     && wget https://github.com/mozilla/geckodriver/releases/download/v0.33.0/geckodriver-v0.33.0-linux64.tar.gz     && tar -xvzf geckodriver-v0.33.0-linux64.tar.gz     && chmod +x geckodriver     && mv geckodriver /usr/local/bin/     && rm geckodriver-v0.33.0-linux64.tar.gz     && rm -rf /var/lib/apt/lists/*  # Clean up apt lists to reduce image size" did not complete successfully: exit code: 100`

**To Reproduce**
run 'docker compose up --build' in MacOS terminal

**Expected behavior**
Installation to complete successfully

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Sequoia 15.3.1 (24D70)

**Smartphone (please complete the following information):**
 - Device: Mac M2 2022

**Additional context**
n/a

**Comment by cristianstoica** [comment]
Fixed by running export DOCKER_DEFAULT_PLATFORM=linux/amd64 in the same term window. Fix might need migrated to Dockerfile.

**Comment by ElishaKay** [comment]
Welcome @cristianstoica 

Thanks for the heads up and good to here that the Dockerfile is working on M2.
It sounds like something like this should help get `docker compose up --build` working for you more seamlessly.

```
services:
  gpt-researcher:
    platform: linux/amd64  # Add this line
    pull_policy: build
    image: gptresearcher/gpt-researcher
    # rest of config...
    
  gptr-nextjs:
    platform: linux/amd64  # Add this line
    pull_policy: build
    # rest of config...
    
  gpt-researcher-tests:
    platform: linux/amd64  # Add this line
    # rest of config...
    
  discord-bot:
    platform: linux/amd64  # Add this line
    # rest of config...
```

If you have a cleaner solution which is backwards-compatible for ubuntu machines as well feel free to go for the PR
